# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170927_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-pub_date', 'title')},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_update_date',
            new_name='update_date',
        ),
    ]
